my-app:
  retention-ms: 300000
  transformer: none

server:
  port: 12001

spring:
  application.name: kafka-streams-gotchas
  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              application:
                server: localhost:${server.port}
      bindings:
        cars:
          destination: cars-topic
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}-group-id
    streams:
      client-id: ${spring.application.name}-client-id
      replication-factor: 1
      #properties:
        #windowstore.changelog.additional.retention.ms: 60000
